site_name: Franzininho WiFi - ESP-IDF
site_favicon: img/favicon.ico

repo_url: https://github.com/Franzininho/exemplos-esp-idf

nav:
    - Primeiros passos: index.md
    - Exemplos:
        - Entrada digital: exemplos/entrada_digital.md
        - Sa√≠da Digital: exemplos/saida_digital.md
    - Sobre: about.md


theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - c
